services:
  - type: web
    name: astro-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: LINE_CHANNEL_SECRET
        sync: false
      - key: LINE_CHANNEL_ACCESS_TOKEN
        sync: false
      - key: GOOGLE_CREDENTIALS_JSON
        sync: false
      - key: GOOGLE_SPREADSHEET_ID
        value: 1u-IDQPi0g-mFxPDetdV46p90xRgLAQZ3Jz90brLl6-M
